name: Chromatic

on:
  workflow_call:

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"
          cache: "npm"
      - name: install
        run: npm ci
      - name: test
        run: npx playwright test
      - name: execute
        run: npm run chromatic
