name: Vercel Production Deployment

on:
  workflow_call:
    secrets:
      vercel-token:
        required: true
      vercel-project-id:
        required: true
      vercel-org-id:
        required: true

env:
  VERCEL_ORG_ID: ${{ secrets.vercel-org-id }}
  VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}

jobs:
  Deploy-Design-Production:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.vercel-token }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.vercel-token }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.vercel-token }}
