name: Vercel Production Site Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SITE_PROJECT_ID }}
on:
  workflow_call:
    secrets:
      vercel-token:
        required: true
jobs:
  Deploy-Site-Production:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.vercel-token }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.vercel-token }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.vercel-token }}
