name: Pull request

on:
  pull_request:
    branches:
      - main
      - rc/**

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
  chromatic:
    uses: ./.github/workflows/chromatic.yml
    secrets:
      chromatic-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
