name: Pull request

on:
  pull_request:
    branches:
      - main
      - rc/**

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
  chromatic:
    uses: ./.github/workflows/chromatic.yml
    secrets:
      npmrc-token: ${{ secrets.JX_GITHUB_BOT_PKG_READ_PAT }}
